import { redirect } from "next/navigation";
import { createClient } from "@/utils/supabase/server";
import { isAdmin } from "@/lib/admin";
import { profile, pipeline, jobs, brain, today, type JobLead, type BrainItem } from "@/data/command-center";
import syncedJobs from "@/data/command-center-jobs.json";
import syncedBrain from "@/data/command-center-brain.json";
import CommandCenterClient from "./CommandCenterClient";

// Brain feed from the vault (scripts/sync-brain.mjs), falling back to the seed.
function buildBrain(): BrainItem[] {
  const feed = syncedBrain as unknown as BrainItem[];
  return feed.length ? feed : brain;
}

// Merge curated leads (command-center.ts) with the scraper feed
// (command-center-jobs.json, regenerated by scripts/sync-jobs.mjs). Curated
// wins on id conflict; sorted by relevance.
function buildJobs(): JobLead[] {
  const feed = syncedJobs as unknown as JobLead[];
  const byId = new Map<string, JobLead>();
  for (const j of jobs.concat(feed)) if (!byId.has(j.id)) byId.set(j.id, j);
  return Array.from(byId.values()).sort((a, b) => b.relevance - a.relevance);
}

export const metadata = {
  title: "BVN Command Center",
};

// Private command center — always fresh, never cached.
export const dynamic = "force-dynamic";

export default async function CommandPage() {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) redirect("/login");
  if (!isAdmin(user.email)) redirect("/dashboard");

  return (
    <CommandCenterClient
      adminEmail={user.email!}
      profile={profile}
      pipeline={pipeline}
      jobs={buildJobs()}
      brain={buildBrain()}
      today={today}
    />
  );
}
