export interface CaseStudy {
  company: string;
  country: string;
  flag: string;
  industry: string;
  challenge: string;
  solution: string;
  results: string[];
  metric: string;
  metricLabel: string;
}

export interface Testimonial {
  name: string;
  role: string;
  company: string;
  country: string;
  avatar: string;
  rating: number;
  text: string;
}

export interface MarketingService {
  slug: string;
  title: string;
  shortDesc: string;
  heroHeadline: string;
  heroSubtext: string;
  color: string;
  features: { title: string; desc: string }[];
  caseStudies: CaseStudy[];
  testimonials: Testimonial[];
  demoType: string;
}

export const marketingServices: MarketingService[] = [
  {
    slug: "social-media-management",
    title: "Social Media Management",
    shortDesc: "Full-service social presence management across all major platforms.",
    heroHeadline: "Build a Brand People Can't Stop Talking About.",
    heroSubtext: "We manage your entire social presence — strategy, content, scheduling, community engagement, and analytics across every platform that matters.",
    color: "orange",
    features: [
      { title: "Multi-Platform Management", desc: "Facebook, Instagram, TikTok, LinkedIn, X, YouTube — one unified strategy." },
      { title: "Content Creation", desc: "Scroll-stopping graphics, captions, and short-form videos crafted by creatives." },
      { title: "Community Management", desc: "Real-time replies, DM handling, and audience engagement to build loyalty." },
      { title: "Analytics & Reporting", desc: "Monthly performance reports with reach, engagement, and growth insights." },
      { title: "Competitor Analysis", desc: "Track what's working in your niche and stay ahead of the competition." },
      { title: "Campaign Management", desc: "Seasonal campaigns, product launches, and viral content strategies." },
    ],
    caseStudies: [
      {
        company: "Maple & Vine Bakery",
        country: "Canada",
        flag: "🇨🇦",
        industry: "Food & Beverage",
        challenge: "A family-owned artisan bakery with 3 locations had under 200 social media followers and was losing foot traffic to larger chain cafés despite having a superior product.",
        solution: "Built a community-first Instagram and Facebook strategy centered on behind-the-scenes baking content, seasonal product reveals, and user-generated photo reposts — making customers feel like insiders.",
        results: [
          "Grew from 200 to 18,400 followers across platforms in 8 months",
          "Online pre-orders increased 240% — now the primary revenue driver",
          "Three seasonal campaign posts each earned 15,000+ organic reach",
          "In-store foot traffic up 65% attributed directly to social media discovery",
        ],
        metric: "240%",
        metricLabel: "Online Order Increase",
      },
      {
        company: "Gear Republic",
        country: "Australia",
        flag: "🇦🇺",
        industry: "Outdoor Retail",
        challenge: "A two-store outdoor equipment retailer had a stagnant 1,200-follower Instagram account and struggled to compete against large online retailers on social media.",
        solution: "Launched a TikTok and Instagram Reels strategy showcasing product reviews, adventure trip content, and staff gear picks — building a genuine outdoor community rather than a sales feed.",
        results: [
          "Instagram grew from 1,200 to 22,000 followers in 10 months",
          "TikTok product videos accumulated 340,000 organic views",
          "Revenue from social-driven traffic up 180% year-over-year",
          "Engagement rate of 4.2% vs. 1.1% industry average",
        ],
        metric: "22K",
        metricLabel: "Followers in 10 Months",
      },
    ],
    testimonials: [
      { name: "Sarah Mitchell", role: "Marketing Director", company: "NovaTech Solutions", country: "Australia", avatar: "SM", rating: 5, text: "Our Instagram engagement tripled in the first 90 days. BVN's team understood our brand voice immediately and created content that genuinely resonated with our audience." },
      { name: "James Okafor", role: "CEO", company: "Okafor Retail Group", country: "United Kingdom", avatar: "JO", rating: 5, text: "We went from 2,000 to 45,000 followers in six months across platforms. The community management alone has saved us two full-time hires." },
      { name: "Lena Fischer", role: "Brand Manager", company: "FreshBite GmbH", country: "Germany", avatar: "LF", rating: 5, text: "BVN handled our entire social calendar across 5 platforms. The content quality is exceptional and engagement rates consistently outperform industry averages." },
      { name: "Carlos Mendez", role: "Founder", company: "Mendez Apparel", country: "United States", avatar: "CM", rating: 5, text: "I had zero social media skills and BVN built everything from scratch. Best business investment I made this year — revenue from social channels is up 180%." },
      { name: "Priya Sharma", role: "Digital Lead", company: "Axis Ventures", country: "Singapore", avatar: "PS", rating: 4, text: "Professional, responsive, and genuinely creative. They handled our product launch social campaign flawlessly and we exceeded our follower targets by 40%." },
      { name: "Tom Nguyen", role: "E-commerce Manager", company: "Vitality Store", country: "Canada", avatar: "TN", rating: 5, text: "Our TikTok went from 0 to 80K followers in 4 months. Three of our videos went viral and directly drove measurable product sales." },
      { name: "Emma Clarke", role: "CMO", company: "Bloom Beauty UK", country: "United Kingdom", avatar: "EC", rating: 5, text: "BVN manages 6 social accounts for us. The reporting dashboard they provide gives us clear ROI visibility — no more guessing what's working." },
      { name: "David Park", role: "Startup Founder", company: "StackFlow", country: "South Korea", avatar: "DP", rating: 4, text: "Exceptional content quality and strategic thinking. They positioned us as thought leaders in our space within months. LinkedIn followers up 220%." },
    ],
    demoType: "social-media",
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    shortDesc: "Data-driven paid campaigns across Google, Meta, and programmatic platforms.",
    heroHeadline: "Reach the Right People. At the Right Time. Every Time.",
    heroSubtext: "We run precision-targeted campaigns across Google Ads, Meta Ads, and programmatic platforms — engineered to maximize ROI and scale your customer acquisition.",
    color: "orange",
    features: [
      { title: "Google Ads Management", desc: "Search, Display, Shopping, and YouTube campaigns optimized for maximum ROI." },
      { title: "Meta Ads (Facebook/Instagram)", desc: "Audience-targeted campaigns with creative testing and retargeting funnels." },
      { title: "Programmatic Advertising", desc: "Automated ad buying across premium publisher networks at scale." },
      { title: "Conversion Rate Optimization", desc: "Landing page optimization and A/B testing to improve ad-to-sale conversion." },
      { title: "Remarketing Campaigns", desc: "Re-engage website visitors and cart abandoners with personalized ads." },
      { title: "Performance Analytics", desc: "Real-time dashboards tracking ROAS, CPC, CTR, and revenue attribution." },
    ],
    caseStudies: [
      {
        company: "HomeNest Interiors",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Home Décor E-commerce",
        challenge: "A small home décor e-commerce store was spending £800/month on Google Ads with a 1.4x ROAS — barely breaking even — and had never tested Meta Ads despite having strong product photography.",
        solution: "Restructured Google Shopping campaigns with tighter product groups and negative keywords, then launched Meta retargeting using dynamic product ads — turning browse abandoners into buyers within 48 hours.",
        results: [
          "Google Ads ROAS improved from 1.4x to 5.2x on the same monthly budget",
          "Meta Ads CPA reduced from £38 to £14 within 45 days",
          "Monthly revenue grew from £12,000 to £54,000 in 6 months",
          "Returning customer rate increased 38% through retargeting sequences",
        ],
        metric: "5.2x",
        metricLabel: "Google Ads ROAS",
      },
      {
        company: "PetBliss",
        country: "Germany",
        flag: "🇩🇪",
        industry: "Pet Supplies E-commerce",
        challenge: "An online pet food and accessories shop was running broad-match Google campaigns with high CPCs and no audience segmentation — spending €1,200/month with little measurable return.",
        solution: "Rebuilt campaigns around high-intent branded and category keywords, implemented Google Shopping with optimized product feeds, and layered in Meta Ads targeting pet owner demographics with seasonal promotions.",
        results: [
          "Google Shopping ROAS reached 4.8x within 60 days of restructuring",
          "Cost per new customer reduced from €42 to €18 through precise targeting",
          "New customer acquisitions up 280% in the first 4 months",
          "Monthly revenue grew by €38,000 attributable to paid channels",
        ],
        metric: "280%",
        metricLabel: "New Customer Growth",
      },
    ],
    testimonials: [
      { name: "Anthony Ross", role: "Performance Marketing Head", company: "ScaleUp Agency", country: "United States", avatar: "AR", rating: 5, text: "BVN brought our Google Ads ROAS from 2.1x to 6.8x in 60 days. Their keyword strategy and bid management is genuinely best-in-class." },
      { name: "Sophie Laurent", role: "E-commerce Director", company: "Maison Mode", country: "France", avatar: "SL", rating: 5, text: "Meta Ads performance improved dramatically. Our CPM dropped 40% and conversion rate doubled after BVN restructured our campaigns." },
      { name: "Raj Patel", role: "Founder", company: "HealthVibe UK", country: "United Kingdom", avatar: "RP", rating: 5, text: "We were burning money on Google Ads before BVN. They rebuilt our entire account structure and our ROAS went from 1.8x to 5.4x within 45 days." },
      { name: "Nina Kovac", role: "CMO", company: "Adriatic Tours", country: "Croatia", avatar: "NK", rating: 4, text: "BVN managed our seasonal campaigns across Google and Meta. Bookings up 220% YoY with a 35% lower cost per booking than the previous year." },
      { name: "Marcus Webb", role: "Growth Lead", company: "Fintech Stack", country: "Australia", avatar: "MW", rating: 5, text: "Programmatic campaigns for our SaaS product were set up and optimized within two weeks. We reached 2.3M qualified impressions in the first month." },
      { name: "Yuki Tanaka", role: "Marketing Manager", company: "Zen Commerce", country: "Japan", avatar: "YT", rating: 5, text: "Cross-platform ad management across Google, Meta and LinkedIn was seamless. BVN's reporting made it easy to understand where every dollar went." },
      { name: "Lisa Baumann", role: "COO", company: "SwissGrowth AG", country: "Switzerland", avatar: "LB", rating: 4, text: "Excellent strategic approach to performance marketing. Our qualified lead volume doubled while keeping cost per lead within our target threshold." },
    ],
    demoType: "digital-marketing",
  },
  {
    slug: "seo",
    title: "Search Engine Optimization",
    shortDesc: "Dominate search rankings with proven technical and content SEO strategies.",
    heroHeadline: "Rank Higher. Get Found. Grow Organically.",
    heroSubtext: "We build sustainable organic search presence through technical SEO, high-authority link building, and content strategy that drives qualified traffic to your business.",
    color: "orange",
    features: [
      { title: "Technical SEO Audit", desc: "Crawlability, Core Web Vitals, site structure, and indexing optimization." },
      { title: "Keyword Strategy", desc: "In-depth research to identify high-value, achievable keyword opportunities." },
      { title: "On-Page Optimization", desc: "Title tags, meta descriptions, headers, internal linking, and content optimization." },
      { title: "Link Building", desc: "High-authority backlink acquisition through outreach, PR, and digital partnerships." },
      { title: "Local SEO", desc: "Google Business Profile optimization and local citation building for location-based businesses." },
      { title: "SEO Content", desc: "Long-form blog posts and landing pages engineered to rank and convert." },
    ],
    caseStudies: [
      {
        company: "Ridgeline Plumbing",
        country: "United States",
        flag: "🇺🇸",
        industry: "Home Services",
        challenge: "A regional plumbing company with 12 technicians had zero online visibility — all business came from referrals and a Yellow Pages listing, and the owner wanted to reduce dependence on word-of-mouth.",
        solution: "Optimized the Google Business Profile, built location-specific service pages for 8 suburbs, fixed 34 technical SEO errors, and executed a local citation building campaign across 60+ directories.",
        results: [
          "Ranked #1 in Google Maps for 'plumber [city]' and 11 surrounding suburbs",
          "Organic inbound leads grew from 3 per month to 28 per month in 5 months",
          "Website traffic up 420% — almost entirely from targeted local searches",
          "Phone calls from Google Search up 185% with measurable booking conversion",
        ],
        metric: "420%",
        metricLabel: "Website Traffic Growth",
      },
      {
        company: "SunCraft Solar",
        country: "Australia",
        flag: "🇦🇺",
        industry: "Renewable Energy Installation",
        challenge: "A solar panel installation company was invisible online despite years in business — all competitors on page 1 were national franchises with large content teams and established domain authority.",
        solution: "Built a content strategy around state-specific solar rebate guides, comparison pages, and FAQ content targeting long-tail residential solar queries — combined with a regional link building campaign targeting local news and trade publications.",
        results: [
          "Achieved page 1 rankings for 28 solar-related keywords across 3 states",
          "Organic quote requests grew from 4 to 31 per month in 7 months",
          "Domain authority increased from 12 to 34 through targeted link building",
          "SEO now accounts for 45% of all new business — displacing paid referral sources",
        ],
        metric: "31",
        metricLabel: "Monthly Organic Leads",
      },
    ],
    testimonials: [
      { name: "Oliver Bennett", role: "Head of Growth", company: "Clarity SaaS", country: "United Kingdom", avatar: "OB", rating: 5, text: "BVN took us from page 5 to page 1 for our primary keyword within 4 months. Organic leads are now our #1 acquisition channel." },
      { name: "Amara Diallo", role: "Founder", company: "Verde Organic", country: "France", avatar: "AD", rating: 5, text: "Technical SEO audit uncovered 47 critical issues we had no idea about. After fixes, Google impressions increased 340% in 8 weeks." },
      { name: "Kevin Zhang", role: "Digital Director", company: "Pacific Rim Commerce", country: "Australia", avatar: "KZ", rating: 5, text: "Link building campaign delivered 38 high-DA backlinks in 3 months. Our domain authority went from 18 to 41 and rankings across 200+ keywords improved significantly." },
      { name: "Isabella Romano", role: "CMO", company: "Casa Bella Interiors", country: "Italy", avatar: "IR", rating: 5, text: "Local SEO work helped us rank in the Google 3-pack for 15 high-value local keywords. Foot traffic increased 65% over 6 months." },
      { name: "Nathan Brooks", role: "E-commerce Manager", company: "Spark Home Goods", country: "United States", avatar: "NB", rating: 4, text: "SEO-optimized product pages and category content drove a 290% increase in non-branded organic traffic. Best ROI channel we run." },
      { name: "Hanna Müller", role: "Marketing Lead", company: "Alpentech GmbH", country: "Germany", avatar: "HM", rating: 5, text: "International SEO setup for our German and English sites was expertly handled. We now rank on page 1 in 3 countries for our key terms." },
      { name: "James O'Brien", role: "CEO", company: "Dublin Digital Co.", country: "Ireland", avatar: "JB", rating: 5, text: "Within 6 months of working with BVN, organic traffic grew 410%. They know what Google actually wants — not just what worked 3 years ago." },
      { name: "Maria Santos", role: "Growth Manager", company: "Porto Ventures", country: "Portugal", avatar: "MS", rating: 4, text: "Their keyword strategy identified 200+ untapped opportunities in our niche. We're now ranking for terms our competitors completely overlooked." },
    ],
    demoType: "seo",
  },
  {
    slug: "email-marketing",
    title: "Email Marketing",
    shortDesc: "Automated sequences and campaigns that convert subscribers into customers.",
    heroHeadline: "Turn Your Email List Into a Revenue Machine.",
    heroSubtext: "We design, write, and automate email campaigns that nurture leads, drive purchases, and build lasting customer relationships — delivering consistent ROI from your existing audience.",
    color: "orange",
    features: [
      { title: "Welcome Sequences", desc: "Automated onboarding flows that convert new subscribers to active customers." },
      { title: "Drip Campaigns", desc: "Multi-step nurture sequences timed perfectly to your buyer journey." },
      { title: "Promotional Campaigns", desc: "Sales emails, flash offers, and seasonal promotions that drive immediate revenue." },
      { title: "Behavioural Triggers", desc: "Abandoned cart, browse abandonment, and post-purchase automated emails." },
      { title: "Newsletter Management", desc: "Regular newsletters that build authority, keep audiences engaged, and drive traffic." },
      { title: "List Segmentation", desc: "Precision targeting by behaviour, demographics, and purchase history." },
    ],
    caseStudies: [
      {
        company: "Boreal Coffee Co.",
        country: "Canada",
        flag: "🇨🇦",
        industry: "Specialty Coffee Subscription",
        challenge: "A specialty coffee roaster offering monthly subscriptions had a 4,200-person email list that they sent one generic newsletter per month — open rates were 14% and unsubscribes were climbing.",
        solution: "Built a segmented email strategy with a personalized welcome sequence for new subscribers, a re-engagement flow for dormant customers, and behavioural triggers based on roast preference and order history.",
        results: [
          "Average open rate improved from 14% to 41% within 3 months",
          "Welcome sequence now converts 34% of free trial users to paid subscribers",
          "Monthly recurring revenue from email-sourced customers reached $22,000",
          "Subscriber churn reduced by 28% through targeted re-engagement flows",
        ],
        metric: "41%",
        metricLabel: "Email Open Rate",
      },
      {
        company: "Velvet Thread Co.",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Craft & Fabric Supplies",
        challenge: "An online fabric and sewing supply shop had a 6,800-subscriber list but no automation — only occasional batch emails that felt impersonal and drove inconsistent revenue spikes.",
        solution: "Implemented abandoned cart recovery sequences, a post-purchase upsell flow, and a segmented newsletter strategy targeting customers by their purchase category (knitting, quilting, embroidery).",
        results: [
          "Abandoned cart emails now recover 24% of carts (up from 8% with a single generic reminder)",
          "Revenue per email send increased 340% through segmented campaigns",
          "Email channel now accounts for 38% of total store revenue",
          "List grew organically from 6,800 to 14,200 subscribers in 12 months",
        ],
        metric: "340%",
        metricLabel: "Revenue Per Email Send",
      },
    ],
    testimonials: [
      { name: "Rachel Kim", role: "E-commerce Director", company: "Bloom & Blossom", country: "United States", avatar: "RK", rating: 5, text: "BVN rebuilt our entire email flow. Abandoned cart recovery alone generates an extra $18,000 per month. Email is now our highest ROI channel." },
      { name: "Florian Bauer", role: "Founder", company: "Bauer Outdoors", country: "Germany", avatar: "FB", rating: 5, text: "Our welcome sequence now converts 28% of new subscribers to buyers within 14 days. BVN's copy and automation setup is exceptional." },
      { name: "Zara Thompson", role: "Marketing Manager", company: "Luminary Beauty", country: "Australia", avatar: "ZT", rating: 5, text: "Open rates jumped from 14% to 38% after BVN optimized our subject lines and segmentation. Revenue from email doubled in the first quarter." },
      { name: "Pierre Dupont", role: "CMO", company: "Éclat Paris", country: "France", avatar: "PD", rating: 4, text: "BVN designed a full 12-email nurture sequence for our B2B product. It runs fully automated and generates qualified demos weekly without any manual effort." },
      { name: "Liam Fitzgerald", role: "CEO", company: "Cork Tech Hub", country: "Ireland", avatar: "LF", rating: 5, text: "Their segmentation strategy was a game-changer. Different sequences for different customer types increased overall email revenue by 145%." },
      { name: "Aiko Watanabe", role: "Growth Lead", company: "Horizon Digital", country: "Japan", avatar: "AW", rating: 5, text: "Campaign emails designed by BVN consistently outperform industry benchmarks. Last Black Friday email drove $42,000 in sales from a 12,000-person list." },
      { name: "Claire Morin", role: "Digital Manager", company: "Soleil Commerce", country: "Belgium", avatar: "CM", rating: 4, text: "Weekly newsletters built by BVN have increased website traffic by 60% from email. Readers genuinely look forward to them — our reply rate proves it." },
    ],
    demoType: "email-marketing",
  },
  {
    slug: "content-marketing",
    title: "Content Marketing",
    shortDesc: "Strategic content that educates, builds authority, and drives conversions.",
    heroHeadline: "Content That Converts. Authority That Lasts.",
    heroSubtext: "We create strategic content that educates your audience, builds your brand authority, and guides prospects from awareness to purchase — turning your website into a lead-generating engine.",
    color: "orange",
    features: [
      { title: "Content Strategy", desc: "Research-backed content calendars aligned to your business goals and audience." },
      { title: "Blog & Article Writing", desc: "SEO-optimized long-form posts that rank, educate, and convert readers." },
      { title: "Infographics & Visuals", desc: "Data-driven visual content that gets shared and builds backlinks." },
      { title: "Case Studies & White Papers", desc: "In-depth credibility content that accelerates B2B sales cycles." },
      { title: "Video Scripts & Storyboards", desc: "Compelling scripts for explainers, YouTube, and product demos." },
      { title: "Content Distribution", desc: "Multi-channel amplification to maximize the reach of every piece created." },
    ],
    caseStudies: [
      {
        company: "Peak Physio",
        country: "New Zealand",
        flag: "🇳🇿",
        industry: "Healthcare / Physiotherapy",
        challenge: "A physiotherapy clinic with 3 practitioners had no content strategy — their website had 4 pages and generated almost no organic traffic, relying entirely on GP referrals and word-of-mouth.",
        solution: "Developed a content plan targeting patient education: injury prevention guides, exercise video scripts, and condition-specific FAQs that answered what potential patients were already searching for.",
        results: [
          "Monthly blog visitors grew from 180 to 4,900 in 6 months",
          "Content now drives 40% of all new patient enquiries — more than any other channel",
          "12 blog articles ranking on page 1 for local physiotherapy-related searches",
          "Average time-on-site doubled as patients pre-educate before booking",
        ],
        metric: "4,900",
        metricLabel: "Monthly Blog Visitors",
      },
      {
        company: "Craft & Clay Studio",
        country: "Ireland",
        flag: "🇮🇪",
        industry: "Crafts & Hobby Supplies",
        challenge: "A ceramics and crafts supply shop with an online store had solid products but no digital presence — only 320 monthly website visitors and no content strategy beyond occasional social posts.",
        solution: "Built a YouTube tutorial series and accompanying blog content around popular craft techniques — driving search traffic that converted readers into first-time buyers through contextual product recommendations.",
        results: [
          "Monthly unique website visitors grew from 320 to 8,400 in 8 months",
          "Online shop revenue grew 195% driven by content-referral traffic",
          "Email list grew by 3,200 new subscribers through content opt-in offers",
          "YouTube tutorial series earned 85,000 views with zero paid promotion",
        ],
        metric: "195%",
        metricLabel: "Online Revenue Growth",
      },
    ],
    testimonials: [
      { name: "Thomas Berger", role: "Marketing Director", company: "Alpine Solutions AG", country: "Switzerland", avatar: "TB", rating: 5, text: "BVN's content strategy transformed our blog from a ghost town to our top lead source. We went from 2 leads/month from content to 45 in six months." },
      { name: "Grace Obi", role: "Content Lead", company: "Meridian Finance", country: "United Kingdom", avatar: "GO", rating: 5, text: "White papers and case studies produced by BVN are used in our sales process daily. Close rates on deals where we share BVN-produced content are 30% higher." },
      { name: "Anders Eriksson", role: "Head of Digital", company: "NordTech AB", country: "Sweden", avatar: "AE", rating: 4, text: "Consistent blog output from BVN has made us a recognized thought leader in our industry. Prospects now come to us pre-educated on our solutions." },
      { name: "Monica Adeyemi", role: "Founder", company: "Adeyemi Consulting", country: "Nigeria", avatar: "MA", rating: 5, text: "Content quality is exceptional. BVN understands our tone and audience perfectly — it reads like we wrote it, only much better." },
      { name: "Patrick Howell", role: "CMO", company: "Howell Media Group", country: "United States", avatar: "PH", rating: 5, text: "Our content calendar covers every stage of the funnel. BVN built a system that produces consistent, high-quality content without requiring constant oversight from our team." },
      { name: "Nadia Petrov", role: "Digital Strategist", company: "Black Sea Digital", country: "Bulgaria", avatar: "NP", rating: 4, text: "Infographics and data visualizations made our research shareable. One BVN-produced infographic earned 120 backlinks and 40,000 shares in a month." },
      { name: "Michael Chen", role: "VP Marketing", company: "Quantum Analytics", country: "Singapore", avatar: "MC", rating: 5, text: "BVN turns complex technical topics into accessible, engaging content. Our technical blog now drives 25% of all inbound leads — up from essentially zero." },
    ],
    demoType: "content-marketing",
  },
  {
    slug: "video-marketing",
    title: "Video Marketing",
    shortDesc: "From short-form reels to full brand films that capture attention and drive action.",
    heroHeadline: "Stop the Scroll. Start the Conversation.",
    heroSubtext: "We produce compelling video content — from 15-second social reels to full brand documentaries — that captures attention, communicates value, and drives measurable business results.",
    color: "orange",
    features: [
      { title: "Short-Form Video (Reels/TikTok)", desc: "Scroll-stopping 15–60 second videos optimized for Instagram, TikTok, and YouTube Shorts." },
      { title: "Brand Story Videos", desc: "Cinematic brand documentaries that build emotional connection with your audience." },
      { title: "Product Demo Videos", desc: "Clear, compelling product walkthroughs that accelerate purchase decisions." },
      { title: "Testimonial Videos", desc: "Professionally produced customer stories that build trust and social proof." },
      { title: "Explainer Animations", desc: "2D/3D animated videos that simplify complex products or concepts." },
      { title: "Video Ads", desc: "Performance-engineered video ads optimized for YouTube, Meta, and programmatic." },
    ],
    caseStudies: [
      {
        company: "Iron Bound Fitness",
        country: "United States",
        flag: "🇺🇸",
        industry: "Fitness Equipment",
        challenge: "A small fitness equipment brand selling resistance bands and home gym accessories was running only static image ads with a 0.6% CTR — struggling to explain product benefits without a demonstration.",
        solution: "Produced a series of 30-second product demo videos showing real workouts, paired with a brand story video focused on the founder's journey — distributed across Meta Ads, Instagram Reels, and YouTube Shorts.",
        results: [
          "Video ad CTR improved from 0.6% to 3.8% — cutting cost per click by 62%",
          "Product demo video drove 450 orders in its first 30 days (vs. typical 12/month)",
          "Instagram Reels averaged 85,000 views per video across 3 months",
          "Annual revenue grew 290% year-over-year after shifting to video-first content",
        ],
        metric: "290%",
        metricLabel: "Revenue Growth YoY",
      },
      {
        company: "Nordic Glow Skincare",
        country: "Sweden",
        flag: "🇸🇪",
        industry: "Natural Skincare",
        challenge: "A natural skincare brand with a loyal but small customer base needed to communicate complex ingredient benefits and sustainability values to a skeptical audience without a large advertising budget.",
        solution: "Created a 90-second brand story video, a series of ingredient explainer Reels, and a TikTok content plan mixing education with behind-the-scenes production content — building trust through transparency.",
        results: [
          "Brand story video was shared 4,200 times organically in the first month",
          "TikTok product videos accumulated 280,000 views within 60 days of launch",
          "Conversion rate on product pages featuring video: 6.2% vs. 1.8% without",
          "Launch campaign video supported 2,400 units sold in the first week",
        ],
        metric: "6.2%",
        metricLabel: "Conversion Rate with Video",
      },
    ],
    testimonials: [
      { name: "Ethan Cross", role: "Founder", company: "CrossFit Collective", country: "United States", avatar: "EC", rating: 5, text: "BVN produced 12 short-form videos for our brand launch. One of them went semi-viral on Instagram — 2.3M views and 800 new memberships in a week." },
      { name: "Camille Bernard", role: "Brand Director", company: "Lumière Cosmetics", country: "France", avatar: "CB", rating: 5, text: "The brand story video BVN created for us is breathtaking. It communicates our values in 90 seconds in a way years of written marketing couldn't." },
      { name: "Daniel Kowalski", role: "Marketing Manager", company: "PolishTech Labs", country: "Poland", avatar: "DK", rating: 5, text: "Explainer animation for our SaaS product reduced our average sales cycle by 40%. Prospects 'get it' immediately when they watch the video." },
      { name: "Sandra Osei", role: "CEO", company: "Accra Digital Agency", country: "Ghana", avatar: "SO", rating: 4, text: "Product demo video drove a 180% increase in free trial signups in the month after launch. The quality exceeded what I'd seen from much larger agencies." },
      { name: "Kenji Matsuda", role: "E-commerce Head", company: "Tokyo Goods Co.", country: "Japan", avatar: "KM", rating: 5, text: "Short-form video ads produced by BVN consistently outperform our static image ads by 3–4x on Meta. We now run video exclusively for paid social." },
      { name: "Ingrid Larsson", role: "CMO", company: "Scandi Living", country: "Denmark", avatar: "IL", rating: 5, text: "Testimonial video series created by BVN is our strongest sales tool. Having real customers talk about our product closes deals that no brochure could." },
    ],
    demoType: "video-marketing",
  },
  {
    slug: "influencer-marketing",
    title: "Creator & Influencer Marketing",
    shortDesc: "Connect with the right creators to build credibility and drive authentic reach.",
    heroHeadline: "Your Next Customer Trusts a Creator More Than an Ad.",
    heroSubtext: "We identify, vet, and manage influencer partnerships that expand your reach authentically — connecting your brand with creators who genuinely resonate with your target audience.",
    color: "orange",
    features: [
      { title: "Influencer Discovery & Vetting", desc: "AI-powered matching of creators by audience demographics, engagement rates, and brand safety." },
      { title: "Campaign Strategy", desc: "Full campaign planning from brief to content guidelines and FTC compliance." },
      { title: "Micro-Influencer Networks", desc: "High-engagement nano and micro-influencers with authentic, niche audiences." },
      { title: "Performance Tracking", desc: "Real-time ROI tracking across all creator posts — reach, engagement, clicks, and conversions." },
      { title: "Long-Term Ambassador Programs", desc: "Ongoing brand ambassador relationships that build sustained audience trust." },
      { title: "Creator Content Rights", desc: "Licensing creator content for use in paid ads for maximum efficiency." },
    ],
    caseStudies: [
      {
        company: "Little Luna Toys",
        country: "Netherlands",
        flag: "🇳🇱",
        industry: "Sustainable Children's Toys",
        challenge: "A sustainable toy brand with beautiful products but minimal marketing budget needed to break into the parenting community online — competing against mass-market brands with far larger ad spend.",
        solution: "Partnered with 15 parenting micro-influencers (10K–80K followers) who authentically shared the brand's sustainability values — providing each with a curated toy set and a unique discount code to track performance.",
        results: [
          "Tracked $42,000 in direct sales via creator discount codes in the first 90 days",
          "Average engagement rate on creator posts: 8.4% vs. 1.9% brand average",
          "Instagram following grew from 800 to 14,000 in 4 months organically",
          "Customer acquisition cost via creators was 55% lower than Meta Ads",
        ],
        metric: "$42K",
        metricLabel: "Creator-Driven Sales",
      },
      {
        company: "Bark & Brew Co.",
        country: "United States",
        flag: "🇺🇸",
        industry: "Premium Pet Treats",
        challenge: "A small-batch dog treat company with an excellent product had no brand awareness outside their local farmers market — unable to scale online sales without a credible distribution channel.",
        solution: "Built an ambassador program with 22 dog lifestyle creators on Instagram and TikTok — selected for authentic pet content rather than follower count — using gifting and commission-based partnerships.",
        results: [
          "Creator content generated 1.2 million total impressions in the first 6 months",
          "Revenue from influencer channel reached $58,000 in the first 6 months",
          "Cost per acquisition via creators was 60% lower than equivalent paid ad spend",
          "Secured two wholesale accounts directly attributed to creator campaign visibility",
        ],
        metric: "1.2M",
        metricLabel: "Total Impressions",
      },
    ],
    testimonials: [
      { name: "Valentina Rossi", role: "Brand Manager", company: "Bella Vita Skincare", country: "Italy", avatar: "VR", rating: 5, text: "BVN matched us with 12 beauty creators who were genuinely perfect for our brand. Sales from creator discount codes tracked to $85,000 in the first month." },
      { name: "Ben Harrington", role: "Founder", company: "Harrington Fitness", country: "United Kingdom", avatar: "BH", rating: 5, text: "Micro-influencer campaign was far more effective than the mega-influencer we'd previously tried. Better engagement, more authentic — and 60% cheaper per conversion." },
      { name: "Mei Liu", role: "E-commerce Director", company: "Jade Fashion Group", country: "China", avatar: "ML", rating: 4, text: "BVN built us an ambassador program from scratch. We now have 30 active creators posting monthly — it runs like clockwork with minimal oversight from our team." },
      { name: "Aleksei Volkov", role: "CMO", company: "Moscow Craft Spirits", country: "Russia", avatar: "AV", rating: 5, text: "International creator network access through BVN opened markets we couldn't enter alone. Creator content in English-speaking markets drove unexpected export demand." },
      { name: "Francesca Bianchi", role: "Marketing Head", company: "Bianchi Jewellery", country: "Italy", avatar: "FB", rating: 5, text: "Long-term ambassador relationships built by BVN have become core brand assets. Our top creator partner generates more trust with her audience than any ad ever could." },
      { name: "Chris Park", role: "Founder", company: "Seoul Snacks", country: "South Korea", avatar: "CP", rating: 4, text: "BVN found food creators that perfectly matched our Korean snack brand. Their content felt native to each platform and generated strong click-through to our Shopify store." },
      { name: "Anya Petrova", role: "Growth Manager", company: "Bloom Wellness", country: "Russia", avatar: "AP", rating: 5, text: "The performance tracking dashboard BVN provides for influencer campaigns is excellent — we can see exactly which creators are driving conversions in real time." },
    ],
    demoType: "influencer-marketing",
  },
  {
    slug: "web-development",
    title: "Web Development",
    shortDesc: "Beautiful, fast websites built to convert visitors into customers.",
    heroHeadline: "Your Website Should Work as Hard as You Do.",
    heroSubtext: "We design and build beautiful, fast, conversion-optimized websites on WordPress and modern tech stacks — every pixel crafted to turn visitors into paying customers.",
    color: "orange",
    features: [
      { title: "Custom WordPress Development", desc: "Bespoke WordPress sites with custom themes, plugins, and performance optimization." },
      { title: "E-commerce Development", desc: "WooCommerce and Shopify stores built for high-conversion shopping experiences." },
      { title: "Landing Page Design", desc: "High-converting landing pages for products, ads, and lead generation campaigns." },
      { title: "Performance Optimization", desc: "Core Web Vitals, speed optimization, and caching for sub-2-second load times." },
      { title: "CMS Integration", desc: "Easy-to-manage content systems so your team can update without developers." },
      { title: "Ongoing Maintenance", desc: "Security updates, backups, performance monitoring, and content updates." },
    ],
    caseStudies: [
      {
        company: "Summit Law Group",
        country: "United States",
        flag: "🇺🇸",
        industry: "Legal Services",
        challenge: "A boutique law firm with 8 attorneys had a dated website loading in 8 seconds with a 74% bounce rate — costing them qualified leads to competitors who ranked below them but had faster, clearer sites.",
        solution: "Redesigned the site with a practice-area-first navigation structure, added a clear consultation booking form above the fold, optimized all images, and implemented caching — reducing load time to 1.4 seconds.",
        results: [
          "Contact form submissions increased 285% within 60 days of launch",
          "Page load time reduced from 8.2 seconds to 1.4 seconds",
          "Bounce rate dropped from 74% to 38% — visitors now exploring the full site",
          "Online consultation bookings reduced admin scheduling time by 12 hours per week",
        ],
        metric: "285%",
        metricLabel: "Lead Form Increase",
      },
      {
        company: "Blue Petal Florist",
        country: "Australia",
        flag: "🇦🇺",
        industry: "Flower Delivery",
        challenge: "A boutique florist was taking 90% of orders by phone — their existing website had no online ordering and lost customers who didn't want to call, especially younger buyers used to ordering online.",
        solution: "Built a Shopify store with a custom product builder for bouquets, same-day delivery slot booking, and a mobile-first design — migrating customers from phone orders to a seamless self-service checkout.",
        results: [
          "Online orders now represent 68% of all sales (up from 10% previously)",
          "Mobile conversion rate of 4.8% (up from 1.1% on the old site)",
          "Average order value increased AU$22 through smart upsell recommendations",
          "Phone order admin time reduced by 15 hours per week across the team",
        ],
        metric: "68%",
        metricLabel: "Sales Now Online",
      },
    ],
    testimonials: [
      { name: "Jessica Cole", role: "Founder", company: "Cole Creative Studio", country: "United States", avatar: "JC", rating: 5, text: "BVN built our new WordPress site in 3 weeks — it's faster, more beautiful, and converting at 3x our old site. Finally a developer team that 'gets it'." },
      { name: "Markus Schneider", role: "CEO", company: "Schneider Engineering GmbH", country: "Germany", avatar: "MS", rating: 5, text: "The e-commerce site BVN built for our industrial parts business is exceptional. Orders increased 85% in the first quarter post-launch." },
      { name: "Penelope Wright", role: "Marketing Manager", company: "Wright & Partners", country: "Australia", avatar: "PW", rating: 4, text: "Landing pages built by BVN consistently outperform our previous agency's work. Current best performer converts at 11.4% — industry average is around 3%." },
      { name: "Hiroshi Nakamura", role: "E-commerce Director", company: "Nakamura Trading", country: "Japan", avatar: "HN", rating: 5, text: "Shopify store built by BVN is beautiful and lightning fast. Mobile conversion rate is up 140% compared to our previous site." },
      { name: "Amelia Foster", role: "COO", company: "Foster Health Group", country: "United Kingdom", avatar: "AF", rating: 5, text: "Professional, thorough, and truly excellent web developers. Our new site loads in under 1 second and the UX has dramatically reduced our support ticket volume." },
      { name: "Lorenzo Conti", role: "Founder", company: "Conti Restaurant Group", country: "Italy", avatar: "LC", rating: 5, text: "BVN built our restaurant booking website in 10 days. Online reservations increased 200% in the first month and we've reduced phone enquiries by 60%." },
      { name: "Natasha Ivanova", role: "Marketing Lead", company: "Ivanova Consulting", country: "Russia", avatar: "NI", rating: 4, text: "CMS integration means our team can update the site daily without touching code. BVN built it exactly to our spec and delivered on time and on budget." },
    ],
    demoType: "web-development",
  },
  {
    slug: "app-development",
    title: "App Development",
    shortDesc: "Custom mobile and web applications built to scale with your business.",
    heroHeadline: "Your Vision. Built. Shipped. Scaled.",
    heroSubtext: "We design, develop, and launch custom mobile and web applications from concept to production — engineering solutions that solve real business problems and delight users.",
    color: "orange",
    features: [
      { title: "iOS & Android Development", desc: "Native and cross-platform mobile apps built for performance and user experience." },
      { title: "Web Application Development", desc: "Scalable web apps using React, Next.js, Node.js, and modern frameworks." },
      { title: "UI/UX Design", desc: "Research-driven interface design that delights users and drives adoption." },
      { title: "API Development & Integration", desc: "RESTful APIs and third-party integrations to connect your app ecosystem." },
      { title: "Cloud Infrastructure", desc: "Scalable AWS/GCP/Azure deployments engineered for reliability and growth." },
      { title: "App Maintenance & Support", desc: "Ongoing updates, bug fixes, performance monitoring, and feature additions." },
    ],
    caseStudies: [
      {
        company: "TrailMate",
        country: "Canada",
        flag: "🇨🇦",
        industry: "Outdoor Recreation",
        challenge: "A small team of hiking enthusiasts wanted to build a trail discovery and community app for Canadian hikers — but had no technical co-founder and needed an MVP launched within a tight 12-week budget.",
        solution: "Built a React Native app with offline trail maps, user review system, difficulty ratings, and a community photo feed — using an agile MVP approach to ship core features first and iterate based on user feedback.",
        results: [
          "12,000 downloads in the first 90 days — featured in the App Store's outdoor category",
          "Daily active user rate of 28% — strong for a niche recreation app",
          "Premium subscription conversion: 18% of free users within 60 days",
          "Rated 4.7/5 stars with 800+ reviews after the first season",
        ],
        metric: "12K",
        metricLabel: "Downloads in 90 Days",
      },
      {
        company: "ParkEasy",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Parking & Navigation",
        challenge: "An entrepreneur wanted to solve the frustration of finding parking in a busy UK market town — a niche problem no large app was serving well — but needed a full-stack app with booking and payment integration.",
        solution: "Built an iOS and Android app connecting drivers with 35 local car parks — including real-time space availability, advance booking, and in-app payment — integrated with parking operators via a custom API layer.",
        results: [
          "8,500 active registered users within 6 months of launch",
          "Partnerships secured with 35 local car parks and 3 council-run facilities",
          "Average session duration of 4.2 minutes — users actively using the core feature",
          "App generated £28,000 in booking fee revenue in its first full year",
        ],
        metric: "35",
        metricLabel: "Car Park Partners",
      },
    ],
    testimonials: [
      { name: "Richard Stone", role: "CTO", company: "StoneCloud Systems", country: "United Kingdom", avatar: "RS", rating: 5, text: "BVN delivered our web application 2 weeks ahead of schedule. Code quality is excellent — our internal dev team reviewed it and was genuinely impressed." },
      { name: "Fatima Al-Hassan", role: "CEO", company: "Hassan Logistics", country: "UAE", avatar: "FA", rating: 5, text: "Fleet tracking mobile app built by BVN is exactly what we needed. iOS and Android versions launched simultaneously and both work flawlessly." },
      { name: "Thomas Johansson", role: "Product Manager", company: "Nordic SaaS", country: "Sweden", avatar: "TJ", rating: 4, text: "React web app for our B2B platform was complex — multiple user roles, real-time data, integrations. BVN handled all of it professionally." },
      { name: "Adaora Okonkwo", role: "Founder", company: "Okonkwo Fintech", country: "Nigeria", avatar: "AO", rating: 5, text: "MVP app built in 10 weeks, exactly on budget. Users love it. We've since engaged BVN for the full v2 build — the trust they earned is invaluable." },
      { name: "Pavel Novak", role: "Head of Product", company: "Prague Digital Co.", country: "Czech Republic", avatar: "PN", rating: 5, text: "API development and third-party integrations were handled seamlessly. Our app now connects with 12 external services — all built and documented by BVN." },
      { name: "Clara Dubois", role: "Co-Founder", company: "Dubois EdTech", country: "France", avatar: "CD", rating: 4, text: "Education app with gamification features, user profiles, and payment integration. BVN delivered a polished product our users genuinely enjoy." },
    ],
    demoType: "app-development",
  },
  {
    slug: "crm-solutions",
    title: "CRM Solutions",
    shortDesc: "Implement and optimize CRM systems that close more deals and retain customers.",
    heroHeadline: "Never Lose a Lead. Never Drop the Ball. Ever.",
    heroSubtext: "We implement, configure, and optimize CRM systems tailored to your sales process — giving your team complete pipeline visibility and automating the follow-ups that drive revenue.",
    color: "orange",
    features: [
      { title: "CRM Implementation", desc: "Full setup of HubSpot, Salesforce, Zoho, Pipedrive, or your CRM of choice." },
      { title: "Pipeline Customization", desc: "Sales stages, deal properties, and workflows tailored to your exact sales process." },
      { title: "Data Migration", desc: "Clean, accurate import of existing contacts, deals, and history from any source." },
      { title: "Automation Setup", desc: "Follow-up sequences, task creation, and notifications automated within the CRM." },
      { title: "Team Training", desc: "Hands-on training ensuring full team adoption and consistent data hygiene." },
      { title: "Reporting Dashboards", desc: "Custom reports showing pipeline health, conversion rates, and rep performance." },
    ],
    caseStudies: [
      {
        company: "Cascade HVAC Services",
        country: "United States",
        flag: "🇺🇸",
        industry: "HVAC Installation & Service",
        challenge: "A 22-person HVAC company was tracking leads in a shared spreadsheet — follow-ups were inconsistent, hot leads went cold, and the owner had no visibility into which jobs were in which stage.",
        solution: "Implemented HubSpot CRM with a custom 6-stage pipeline, automated follow-up tasks at each stage, and a text-and-email sequence triggered when new leads came in — cutting average response time from hours to minutes.",
        results: [
          "Lead response time reduced from 4.5 hours to under 12 minutes on average",
          "Quote-to-close rate improved from 18% to 41% through consistent follow-up",
          "Annual revenue increased by $180,000 attributable to better pipeline management",
          "Quote-to-close cycle shortened from 9 days to 3 days",
        ],
        metric: "41%",
        metricLabel: "Quote-to-Close Rate",
      },
      {
        company: "Thornfield Estate Agents",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Real Estate",
        challenge: "A boutique estate agency with 6 agents was losing 32% of their leads to slow follow-up — agents had their own ad-hoc systems and there was no centralized visibility for the principal.",
        solution: "Deployed Pipedrive CRM with vendor and buyer pipeline stages, automated viewing reminder sequences, and a weekly dashboard report for the principal showing pipeline health and agent activity metrics.",
        results: [
          "Lead loss from slow follow-up dropped to under 4% (from 32% previously)",
          "Average property sale time reduced from 78 days to 47 days",
          "Commission revenue grew 35% year-over-year in the 12 months post-implementation",
          "Vendor satisfaction scores improved from 6.8 to 9.1 out of 10",
        ],
        metric: "35%",
        metricLabel: "Revenue Growth",
      },
    ],
    testimonials: [
      { name: "Daniel Brooks", role: "Sales Director", company: "Brooks Capital", country: "United States", avatar: "DB", rating: 5, text: "HubSpot implementation by BVN transformed our sales team. Pipeline visibility went from zero to complete. We closed 35% more deals in Q1 post-implementation." },
      { name: "Katrina Schmidt", role: "Head of Sales", company: "Schmidt Consulting", country: "Germany", avatar: "KS", rating: 5, text: "BVN migrated 8 years of client data into Salesforce without losing a single record. The custom pipeline they built matches our process exactly." },
      { name: "Tobias Jensen", role: "Founder", company: "Jensen Property Group", country: "Denmark", avatar: "TJ", rating: 4, text: "CRM setup changed how we manage leads. We used to lose 30% of enquiries to follow-up failure — now automated sequences handle it and conversion is up 50%." },
      { name: "Chioma Eze", role: "CEO", company: "Eze Business Services", country: "Nigeria", avatar: "CE", rating: 5, text: "BVN set up our Zoho CRM in 10 days and trained our team thoroughly. Sales team adoption rate was 100% — best implementation experience we've had." },
      { name: "Robert Tan", role: "VP Sales", company: "Tan Pacific Holdings", country: "Singapore", avatar: "RT", rating: 5, text: "Custom reporting dashboards give our leadership complete sales pipeline visibility. Forecasting accuracy improved from 55% to 89% after BVN's CRM work." },
      { name: "Brigitte Leroy", role: "CMO", company: "Leroy Group", country: "France", avatar: "BL", rating: 4, text: "Pipedrive was set up beautifully with automations that save our sales team 3 hours per day. ROI was positive within the first month of implementation." },
    ],
    demoType: "crm-solutions",
  },
];

export function getMarketingService(slug: string): MarketingService | undefined {
  return marketingServices.find((s) => s.slug === slug);
}
