import type { CaseStudy, Testimonial } from "./marketing-services";

export interface OperationsService {
  slug: string;
  title: string;
  shortDesc: string;
  heroHeadline: string;
  heroSubtext: string;
  features: { title: string; desc: string }[];
  caseStudies: CaseStudy[];
  testimonials: Testimonial[];
  demoType: string;
}

export const operationsServices: OperationsService[] = [
  {
    slug: "crm-automation",
    title: "CRM & Sales Automation",
    shortDesc: "Automate your entire sales pipeline — from lead capture to close.",
    heroHeadline: "Close More Deals. Work Half as Hard.",
    heroSubtext: "We deploy and automate CRM systems that track every lead, trigger every follow-up, and give you complete pipeline visibility — so your sales team can focus on selling, not admin.",
    features: [
      { title: "Automated Lead Routing", desc: "Instantly assign leads to the right rep based on territory, industry, or deal size." },
      { title: "Follow-Up Sequences", desc: "Multi-step email and SMS sequences triggered automatically at every pipeline stage." },
      { title: "Deal Scoring", desc: "AI-powered lead scoring to prioritize the hottest opportunities first." },
      { title: "Pipeline Automation", desc: "Automatic stage progression, task creation, and stakeholder notifications." },
      { title: "Sales Forecasting", desc: "Predictive revenue forecasting based on current pipeline and historical data." },
      { title: "Integration with Marketing", desc: "Bidirectional data sync with marketing tools for full lead lifecycle visibility." },
    ],
    caseStudies: [
      {
        company: "Ridgewood Staffing Solutions",
        country: "United States",
        flag: "🇺🇸",
        industry: "Recruitment / Staffing",
        challenge: "Ridgewood, a 35-person staffing firm in Ohio, had recruiters manually updating spreadsheets and sending individual follow-up emails — losing hot candidates and clients to faster competitors who responded first.",
        solution: "Deployed a HubSpot CRM with automated lead routing, a 5-step follow-up email sequence triggered on every new enquiry, and deal stage automation that notified recruiters only when action was truly needed.",
        results: [
          "Lead response time dropped from 4 hours to 12 minutes with auto-routing",
          "Recruiters reclaimed 2.5 hours per day previously spent on manual CRM updates",
          "Placement rate improved 38% in 6 months through consistent follow-up automation",
          "Monthly revenue grew 52% in the year following CRM automation rollout",
        ],
        metric: "52%",
        metricLabel: "Revenue Growth in Year 1",
      },
      {
        company: "Birchwood Financial Advisors",
        country: "Canada",
        flag: "🇨🇦",
        industry: "Independent Financial Services",
        challenge: "Birchwood's 12 advisors were managing client relationships entirely through email and sticky notes — missing renewal dates, losing referral opportunities, and struggling to track a growing pipeline of 400+ prospects.",
        solution: "Implemented a Pipedrive CRM with automated renewal reminders, referral tracking workflows, and a deal scoring model that flagged high-intent prospects for immediate advisor outreach.",
        results: [
          "Zero missed client renewal dates since automation went live",
          "Referral conversion rate improved from 18% to 41% with structured follow-up sequences",
          "Pipeline visibility increased — advisors now forecast quarterly revenue with 89% accuracy",
          "AUM grew by CAD $14M in 12 months as warmer leads converted faster",
        ],
        metric: "41%",
        metricLabel: "Referral Conversion Rate",
      },
    ],
    testimonials: [
      { name: "Steven Park", role: "Sales Director", company: "Park Distribution", country: "United States", avatar: "SP", rating: 5, text: "Our sales team now has zero missed follow-ups. The automation BVN built handles every touchpoint — deals move through the pipeline like clockwork." },
      { name: "Elena Kovacs", role: "Head of Sales", company: "Kovacs Systems Hungary", country: "Hungary", avatar: "EK", rating: 5, text: "CRM automation reduced admin work by 4 hours per rep per day. That's time back in front of customers, which directly translated to a 45% increase in closed deals." },
      { name: "William Fraser", role: "Founder", company: "Fraser Properties", country: "United Kingdom", avatar: "WF", rating: 5, text: "Lead routing and automated follow-ups mean we never lose a hot lead to slow response time anymore. Contact-to-meeting rate improved from 12% to 38%." },
      { name: "Yui Nakashima", role: "VP Sales", company: "Nakashima Corp", country: "Japan", avatar: "YN", rating: 4, text: "Salesforce implementation with automation workflows was beyond what we expected. Pipeline visibility and forecast accuracy transformed our quarterly planning." },
      { name: "Olga Petersen", role: "CEO", company: "Petersen Nordic", country: "Norway", avatar: "OP", rating: 5, text: "Deal scoring automation means our reps know exactly where to focus each morning. Win rate on scored leads is 2.8x our overall average." },
      { name: "Kwame Asante", role: "Sales Manager", company: "Asante Technologies", country: "Ghana", avatar: "KA", rating: 4, text: "BVN built automation that syncs our marketing and sales data. We can now see a customer's full journey from first ad click to signed contract." },
      { name: "Claire Whitfield", role: "Commercial Director", company: "Whitfield Pharma", country: "Australia", avatar: "CW", rating: 5, text: "Complex B2B sales cycles are now fully tracked and automated. Every stakeholder in a deal receives the right communication at the right time — automatically." },
    ],
    demoType: "crm-automation",
  },
  {
    slug: "ai-agents",
    title: "AI Agents & Intelligent Automation",
    shortDesc: "AI-powered agents that handle customer service, tasks, and decisions 24/7.",
    heroHeadline: "Your Best Employee Never Sleeps.",
    heroSubtext: "We deploy AI agents that handle customer inquiries, automate complex workflows, generate reports, and make intelligent decisions around the clock — without adding headcount.",
    features: [
      { title: "Customer Service AI", desc: "Conversational AI agents that resolve 70%+ of customer inquiries without human escalation." },
      { title: "Sales Qualification Bot", desc: "AI that qualifies inbound leads, books meetings, and updates your CRM automatically." },
      { title: "Document Processing AI", desc: "Intelligent extraction and processing of contracts, invoices, and forms at scale." },
      { title: "Internal Knowledge Base AI", desc: "Employee-facing AI assistant trained on your internal documentation and processes." },
      { title: "Predictive Analytics AI", desc: "Machine learning models that forecast demand, churn, and revenue with high accuracy." },
      { title: "Workflow Orchestration", desc: "AI-driven orchestration that coordinates multi-step processes across multiple systems." },
    ],
    caseStudies: [
      {
        company: "Sapphire Stays",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Short-Term Rental / Hospitality",
        challenge: "Sapphire Stays, a boutique serviced apartment operator with 22 properties in Bristol, was drowning in repetitive guest enquiries via email and WhatsApp — often after hours when staff were unavailable, causing missed bookings.",
        solution: "Deployed a conversational AI agent trained on Sapphire's full property listings, pricing, availability, and house rules — handling guest enquiries, sending booking confirmations, and escalating complex requests to staff.",
        results: [
          "73% of guest enquiries resolved by AI without staff involvement",
          "Response time improved from an average of 3.5 hours to under 90 seconds",
          "After-hours booking conversions increased 61% in the first quarter",
          "Staff reclaimed 22 hours per week previously spent on repetitive message replies",
        ],
        metric: "61%",
        metricLabel: "After-Hours Booking Increase",
      },
      {
        company: "Volta Electronics",
        country: "Netherlands",
        flag: "🇳🇱",
        industry: "B2B Electronics Distribution",
        challenge: "Volta, a 45-person electronics distributor in Amsterdam, was manually processing 300+ inbound orders per day — copying data between email, their ERP system, and spreadsheets, resulting in entry errors and delayed confirmations.",
        solution: "Built an AI document processing agent that read incoming order emails, extracted line items and quantities, validated stock levels, and automatically pushed confirmed orders into the ERP — all without human touch.",
        results: [
          "Order processing time reduced from 8 minutes per order to under 40 seconds",
          "Data entry errors dropped 96% — from roughly 30 per week to fewer than 2",
          "Order confirmation sent to customers within 2 minutes vs. same-day previously",
          "Operations team redeployed from data entry to customer relationship management",
        ],
        metric: "96%",
        metricLabel: "Reduction in Data Entry Errors",
      },
    ],
    testimonials: [
      { name: "Jonathan Lee", role: "CTO", company: "Lee Commerce Inc.", country: "United States", avatar: "JL", rating: 5, text: "Our AI customer service agent resolves 74% of inquiries without human involvement. Customer satisfaction actually went UP after implementation — surprising but true." },
      { name: "Anna Kowalczyk", role: "Head of Operations", company: "Warsaw Digital", country: "Poland", avatar: "AK", rating: 5, text: "AI document processing handles 2,000 invoices per day with 99.2% accuracy. What used to require 4 staff members now runs fully automatically." },
      { name: "George Mitchell", role: "CEO", company: "Mitchell Retail Group", country: "United Kingdom", avatar: "GM", rating: 5, text: "The sales qualification AI books 12–15 qualified meetings per week — without a sales development rep on payroll. ROI was positive within 30 days." },
      { name: "Hana Fujimoto", role: "Digital Director", company: "Fujimoto Group", country: "Japan", avatar: "HF", rating: 4, text: "Internal knowledge base AI has transformed how our 200 employees find information. Response quality improved and onboarding time for new staff reduced 50%." },
      { name: "Paul Oduya", role: "Founder", company: "Oduya Ventures", country: "Nigeria", avatar: "PO", rating: 5, text: "AI agent for our e-commerce store handles returns, order tracking, and product questions. We scaled from 500 to 5,000 orders/month without adding support staff." },
      { name: "Ingrid Berg", role: "Operations Manager", company: "Berg Logistics", country: "Norway", avatar: "IB", rating: 5, text: "Workflow orchestration AI coordinates 8 different systems in our fulfillment process. Error rate dropped 94% and throughput doubled after implementation." },
      { name: "Pierre Beaumont", role: "COO", company: "Beaumont Finance", country: "France", avatar: "PB", rating: 4, text: "Predictive churn AI identifies at-risk clients 30 days before they leave. Our retention team now intervenes proactively — churn rate down 35%." },
      { name: "Samira Khalil", role: "Head of Innovation", company: "Gulf Digital Group", country: "UAE", avatar: "SK", rating: 5, text: "AI agents integrated into WhatsApp Business handle our entire Arabic-language customer service operation. Quality and speed exceeded our human team benchmarks." },
    ],
    demoType: "ai-agents",
  },
  {
    slug: "hr-payroll",
    title: "HR & Payroll Automation",
    shortDesc: "Automate your entire HR lifecycle from onboarding to payroll processing.",
    heroHeadline: "HR That Runs Itself. People Who Thrive.",
    heroSubtext: "We automate your complete HR cycle — onboarding, attendance, leave management, and payroll processing — eliminating manual errors and freeing your HR team to focus on your people.",
    features: [
      { title: "Automated Onboarding", desc: "Digital onboarding workflows with e-signatures, document collection, and system access." },
      { title: "Payroll Processing", desc: "Accurate, compliant automated payroll that processes in minutes, not days." },
      { title: "Leave & Attendance Management", desc: "Self-service leave requests, real-time attendance tracking, and automated approvals." },
      { title: "Performance Management", desc: "Automated review cycles, goal tracking, and 360° feedback workflows." },
      { title: "Compliance & Reporting", desc: "Automated compliance reports, tax filings, and statutory submissions." },
      { title: "Employee Self-Service Portal", desc: "Employee portal for payslips, leave balances, profile updates, and document access." },
    ],
    caseStudies: [
      {
        company: "Mesa Construction Group",
        country: "United States",
        flag: "🇺🇸",
        industry: "General Contracting",
        challenge: "Mesa, a 90-person construction company in Phoenix, ran payroll manually every two weeks across four job classifications, union vs. non-union workers, and variable overtime — a two-day process riddled with errors and compliance risk.",
        solution: "Implemented an automated HR and payroll system with digital clock-in tied to job codes, automatic overtime calculations, union rate differentials, and one-click payroll generation reviewed and submitted in under an hour.",
        results: [
          "Payroll processing time reduced from 2 days to under 1 hour per cycle",
          "Payroll errors dropped from an average of 11 per run to zero in 8 consecutive cycles",
          "New hire onboarding completed digitally before first day — from 3 days of paperwork to 45 minutes",
          "HR compliance violations eliminated — automated certified payroll reports for all government projects",
        ],
        metric: "Zero",
        metricLabel: "Payroll Errors for 8 Cycles",
      },
      {
        company: "Cobalt Cleaning Services",
        country: "Australia",
        flag: "🇦🇺",
        industry: "Commercial Cleaning",
        challenge: "Cobalt employed 65 part-time and casual cleaners across Melbourne — tracking attendance via paper timesheets submitted weekly created chronic late payroll, disputes, and a manual data entry burden that consumed their only HR admin's entire week.",
        solution: "Deployed mobile-based digital timesheets with GPS verification, automated leave request approvals, and direct payroll integration that processed weekly wages automatically on Thursday nights without any human involvement.",
        results: [
          "HR admin time on payroll reduced from 30 hours per week to under 3 hours",
          "Timesheet disputes dropped 88% — GPS-verified clock-ins replaced paper-based guesswork",
          "Casual staff paid on time every week for 12 consecutive months — first time in company history",
          "Staff turnover fell 24% attributed to reliable, accurate, on-time pay",
        ],
        metric: "88%",
        metricLabel: "Drop in Timesheet Disputes",
      },
    ],
    testimonials: [
      { name: "Caroline Fenton", role: "HR Director", company: "Fenton Group UK", country: "United Kingdom", avatar: "CF", rating: 5, text: "Payroll that used to take our team 2 days now runs in 3 hours automatically. Zero errors in 6 months. BVN's setup was meticulous and the system is rock solid." },
      { name: "Marco Ferretti", role: "COO", company: "Ferretti Manufacturing", country: "Italy", avatar: "MF", rating: 5, text: "Automated onboarding workflow means new hires complete all documentation before day one. We've reduced onboarding admin from 8 hours to 45 minutes per hire." },
      { name: "Sandra Osei", role: "Head of HR", company: "Osei Hospitality Group", country: "Ghana", avatar: "SO", rating: 4, text: "Leave management automation eliminated the email chaos around approvals. Employees love the self-service portal and our HR team saved 15 hours per week." },
      { name: "Henrik Larsen", role: "CEO", company: "Larsen Nordic", country: "Denmark", avatar: "HL", rating: 5, text: "Multi-currency payroll for our teams in 5 countries now runs automatically. Compliance reports are generated automatically for each jurisdiction. Life-changing for our small HR team." },
      { name: "Priya Krishnan", role: "HR Manager", company: "Krishnan Tech India", country: "India", avatar: "PK", rating: 5, text: "Performance review automation and 360 feedback workflows took our review cycle from 3 weeks of chaos to a structured, consistent 5-day process." },
      { name: "Thomas Mueller", role: "Finance Director", company: "Mueller Pharma", country: "Germany", avatar: "TM", rating: 4, text: "Payroll accuracy is now 100%. The automated compliance reporting for German labor law has saved our HR team 40 hours per month and eliminated late filing risk." },
      { name: "Julia Santos", role: "Operations Lead", company: "Santos Retail Brazil", country: "Brazil", avatar: "JS", rating: 5, text: "HR automation for our 300-person workforce was seamlessly implemented. The employee self-service portal had 95% adoption within the first week." },
    ],
    demoType: "hr-payroll",
  },
  {
    slug: "operations-automation",
    title: "Operations Automation",
    shortDesc: "Digitize and automate your core business workflows and processes.",
    heroHeadline: "Your Business. Running at Full Power. Automatically.",
    heroSubtext: "We map, digitize, and automate your core business processes — purchase orders, approvals, inventory management, and workflows — replacing manual work with intelligent systems that never miss a step.",
    features: [
      { title: "Process Mapping & Analysis", desc: "Comprehensive audit of existing workflows to identify automation opportunities." },
      { title: "Approval Workflow Automation", desc: "Multi-level approval chains for POs, expenses, and contracts — automated and trackable." },
      { title: "Inventory Management Automation", desc: "Real-time inventory tracking with auto-reorder triggers and supplier notifications." },
      { title: "Purchase Order Processing", desc: "End-to-end PO automation from request to vendor confirmation and payment." },
      { title: "Compliance & Audit Trails", desc: "Automatic audit logs, compliance checks, and documentation for every process." },
      { title: "Cross-Department Workflows", desc: "Automated handoffs between departments with SLA tracking and escalation rules." },
    ],
    caseStudies: [
      {
        company: "Stonebridge Bakery Supply",
        country: "United States",
        flag: "🇺🇸",
        industry: "Wholesale Food Distribution",
        challenge: "Stonebridge, a family-owned bakery ingredient distributor in Wisconsin with 28 staff, was processing purchase orders via fax and email — a system that caused frequent duplicate orders, stockouts of key ingredients, and invoice discrepancies.",
        solution: "Automated the full PO lifecycle — online vendor portal, auto-generated purchase orders triggered by low-stock alerts, three-way match between PO, receipt, and invoice, and automated supplier payment scheduling.",
        results: [
          "PO processing time reduced from 3 days to same-day across all vendors",
          "Stockout incidents dropped from 15 per month to 1-2 with auto-reorder triggers",
          "Invoice discrepancies reduced 91% through automated three-way matching",
          "Accounts payable team reduced from 3 people to 1 — two staff redeployed to sales support",
        ],
        metric: "91%",
        metricLabel: "Reduction in Invoice Discrepancies",
      },
      {
        company: "GreenLeaf Nurseries",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Retail Garden & Landscaping",
        challenge: "GreenLeaf operated 4 garden centres in Surrey with seasonal inventory swings of 800+ SKUs — manual stock counts, handwritten reorder lists, and multi-department approval chains made spring restocking a chaotic two-week scramble every year.",
        solution: "Implemented inventory automation with real-time stock levels updated at point of sale, pre-set reorder triggers per SKU, digital approval workflows for purchases over £500, and auto-generated seasonal purchase plans based on prior-year sales data.",
        results: [
          "Spring restocking process reduced from 2 weeks of chaos to 3 structured days",
          "Out-of-stock incidents during peak season dropped 74% year-over-year",
          "Approval turnaround time for purchase requests reduced from 4 days to 6 hours",
          "Wastage from over-ordering perishable plants reduced by 31%, saving £28,000 annually",
        ],
        metric: "74%",
        metricLabel: "Fewer Out-of-Stock Incidents",
      },
    ],
    testimonials: [
      { name: "Raymond Chan", role: "COO", company: "Chan Manufacturing", country: "Hong Kong", avatar: "RC", rating: 5, text: "Purchase order automation eliminated 3 days of processing time per week. Our procurement team now handles 3x the volume with half the staff time." },
      { name: "Victoria Hughes", role: "Operations Director", company: "Hughes Distribution", country: "United Kingdom", avatar: "VH", rating: 5, text: "Approval workflow automation means nothing gets stuck waiting for a signature anymore. Process completion times improved by 70% across all departments." },
      { name: "Frank Delacroix", role: "General Manager", company: "Delacroix Wholesale", country: "France", avatar: "FD", rating: 4, text: "Inventory automation with auto-reorder triggers means we never run out of stock. Carrying costs reduced 25% through smarter automated reordering." },
      { name: "Laura Benson", role: "Head of Operations", company: "Benson Pharma", country: "Australia", avatar: "LB", rating: 5, text: "Compliance automation for pharmaceutical operations is non-negotiable. BVN built audit trails and regulatory checks that our compliance team trusts completely." },
      { name: "Seun Adeyemi", role: "CEO", company: "Adeyemi Enterprises", country: "Nigeria", avatar: "SA", rating: 5, text: "Cross-department workflow automation eliminated the coordination chaos between our 6 departments. Projects now move to completion 40% faster on average." },
      { name: "Marta Gonzalez", role: "Operations Manager", company: "Gonzalez Logistics", country: "Spain", avatar: "MG", rating: 4, text: "End-to-end PO processing that used to take 5 days now completes in 6 hours. The ROI was visible within the first month of going live." },
    ],
    demoType: "operations-automation",
  },
  {
    slug: "time-tracking",
    title: "Time & Location Tracking",
    shortDesc: "Real-time employee tracking for accurate attendance and workforce management.",
    heroHeadline: "Know Where Your Team Is. Know How Time is Spent.",
    heroSubtext: "We implement real-time time tracking and GPS-based location monitoring systems — giving you accurate attendance data, remote workforce visibility, and automated timesheets that eliminate manual errors.",
    features: [
      { title: "GPS Location Tracking", desc: "Real-time location monitoring for field teams, delivery drivers, and remote workers." },
      { title: "Digital Time Clock", desc: "Mobile and web-based clock-in/out with geofencing for location verification." },
      { title: "Automated Timesheets", desc: "Auto-generated timesheets ready for payroll — zero manual data entry required." },
      { title: "Geofence Alerts", desc: "Automatic notifications when employees enter or leave designated work zones." },
      { title: "Project Time Tracking", desc: "Track time by project and task for accurate job costing and billing." },
      { title: "Productivity Analytics", desc: "Work hour patterns, overtime tracking, and productivity insights by team and individual." },
    ],
    caseStudies: [
      {
        company: "Highfield Electrical Contractors",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Electrical Contracting",
        challenge: "Highfield, a 40-person electrical contractor based in Manchester, had engineers submitting handwritten weekly timesheets — creating disputes with clients over billable hours, payroll delays, and an inability to track job profitability accurately.",
        solution: "Rolled out a mobile time-tracking app with job-code clock-in, GPS verification for on-site attendance, and automatic timesheet generation feeding directly into both payroll and job-costing reports for client invoicing.",
        results: [
          "Client billing disputes reduced from 8 per month to zero in the first 3 months",
          "Payroll processing time dropped from 2 days to under 2 hours each week",
          "Job profitability reporting became available in real time — unprofitable contracts identified immediately",
          "Recovered £18,000 in previously unbilled hours in the first 6 months of tracking",
        ],
        metric: "£18K",
        metricLabel: "Recovered in Unbilled Hours",
      },
      {
        company: "Nuvelo Consulting",
        country: "Canada",
        flag: "🇨🇦",
        industry: "Management Consulting (SMB)",
        challenge: "Nuvelo, a boutique consulting firm in Toronto with 18 consultants, billed clients by the hour but tracked time manually in spreadsheets — making monthly invoicing a 3-day process that was consistently late and sometimes inaccurate.",
        solution: "Implemented project-based time tracking integrated with their billing software — consultants logged time against client projects throughout the day, and monthly invoices were auto-generated and dispatched on the 1st of every month.",
        results: [
          "Monthly invoicing cycle reduced from 3 days to 2 hours",
          "Invoice accuracy improved — billing disputes dropped from 5 per month to 0",
          "Consultant utilization visibility enabled better project allocation — billable hours up 17%",
          "Average payment collection time reduced from 38 days to 21 days due to faster, accurate invoicing",
        ],
        metric: "17%",
        metricLabel: "Increase in Billable Hours",
      },
    ],
    testimonials: [
      { name: "Andrew Fletcher", role: "Field Operations Manager", company: "Fletcher Services", country: "United States", avatar: "AF", rating: 5, text: "GPS tracking for our 80-person field team was a game changer. We can see where everyone is in real time and our clients love the accurate arrival ETAs." },
      { name: "Katarina Lindqvist", role: "HR Director", company: "Lindqvist Group", country: "Sweden", avatar: "KL", rating: 5, text: "Automated timesheets integrated with our payroll system save our HR team 15 hours every pay cycle. Zero disputes about hours since implementation." },
      { name: "Emmanuel Obi", role: "Logistics Manager", company: "Obi Deliveries", country: "Nigeria", avatar: "EO", rating: 4, text: "Real-time driver tracking dramatically improved our delivery performance. Customer complaints about late deliveries dropped 80% in the first month." },
      { name: "Lisa Hoffmann", role: "Operations Lead", company: "Hoffmann Construction", country: "Germany", avatar: "LH", rating: 5, text: "Geofencing for our construction sites ensures accurate timekeeping. Payroll accuracy is now 100% and we've eliminated all the manual timesheet fraud." },
      { name: "Colin MacPherson", role: "CEO", company: "MacPherson Facilities", country: "Scotland", avatar: "CM", rating: 5, text: "Project time tracking lets us cost jobs accurately for the first time. We identified 3 contracts that were consistently losing us money — now fixed." },
      { name: "Yuki Hara", role: "Workforce Manager", company: "Hara Corporation", country: "Japan", avatar: "YH", rating: 4, text: "Mobile time clock with geofencing works perfectly for our remote workers. Attendance accuracy improved and manual timesheet entry was completely eliminated." },
    ],
    demoType: "time-tracking",
  },
  {
    slug: "admin-automation",
    title: "Admin Automation",
    shortDesc: "Automate documents, emails, scheduling, and data entry to save hours weekly.",
    heroHeadline: "Stop Doing Admin. Start Running Your Business.",
    heroSubtext: "We automate the repetitive administrative work that consumes your team's day — document generation, email responses, scheduling, data entry, and reporting — so you can focus on what actually grows the business.",
    features: [
      { title: "Document Automation", desc: "Auto-generate contracts, quotes, invoices, and reports from templates and data." },
      { title: "Email Response Automation", desc: "Smart email triage and automated responses for common inquiries." },
      { title: "Scheduling & Calendar Automation", desc: "Automated meeting booking, reminders, and calendar management." },
      { title: "Data Entry Automation", desc: "Eliminate manual data entry with intelligent form processing and data sync." },
      { title: "Reporting Automation", desc: "Scheduled reports auto-generated and distributed to stakeholders automatically." },
      { title: "Invoice & Payment Automation", desc: "Automated invoice creation, delivery, reminders, and payment reconciliation." },
    ],
    caseStudies: [
      {
        company: "Harrow & Reid Solicitors",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Legal Services (SMB Law Firm)",
        challenge: "Harrow & Reid, a 14-solicitor property law firm in Leeds, spent an average of 2.5 hours per file generating client care letters, standard contract templates, and compliance documents — all manually typed from scratch for each new matter.",
        solution: "Built a document automation system that pulled client data from their case management software into pre-approved templates — generating fully populated, compliance-ready documents in one click, ready for solicitor review.",
        results: [
          "Document preparation time reduced from 2.5 hours to 15 minutes per new matter",
          "Solicitor billable hours increased by 11% as admin time was freed up for client work",
          "New client onboarding cycle reduced from 5 days to same-day document dispatch",
          "Compliance document error rate dropped 83% — significantly reducing professional indemnity risk",
        ],
        metric: "83%",
        metricLabel: "Reduction in Document Errors",
      },
      {
        company: "Clearview Accountants",
        country: "Australia",
        flag: "🇦🇺",
        industry: "Accounting & Tax (Boutique Firm)",
        challenge: "Clearview, a 9-person accounting practice in Perth, ran their entire practice on manual scheduling, client follow-up emails, and end-of-month reporting that consumed senior accountants' time on low-value administrative work during tax season.",
        solution: "Automated client email follow-ups for document requests, deployed a self-service scheduling portal, and built automated weekly reports that summarised each client's outstanding items and sent reminders without staff intervention.",
        results: [
          "Senior accountant time on admin reduced by 9 hours per week each during tax season",
          "Client document submission rate improved 47% through automated reminder sequences",
          "Scheduling back-and-forth eliminated — clients book directly, cutting 5 hours/week of phone tag",
          "Practice revenue increased 22% in 12 months as partners focused on advisory, not admin",
        ],
        metric: "22%",
        metricLabel: "Practice Revenue Growth",
      },
    ],
    testimonials: [
      { name: "Harry Williamson", role: "Founder", company: "Williamson Legal", country: "United Kingdom", avatar: "HW", rating: 5, text: "Contract generation that used to take 2 hours per client now takes 8 minutes. BVN's document automation paid for itself in the first week." },
      { name: "Sophie Renard", role: "Office Manager", company: "Renard Associates", country: "France", avatar: "SR", rating: 5, text: "Email automation handles 60% of our inbound enquiries automatically. The quality of responses is excellent and clients can't tell the difference." },
      { name: "Benjamin Ahuna", role: "Operations Manager", company: "Ahuna Services", country: "New Zealand", avatar: "BA", rating: 4, text: "Scheduling automation eliminated the back-and-forth email chains for appointment booking. We save 4 hours per week per staff member on scheduling alone." },
      { name: "Katerina Novakova", role: "Finance Director", company: "Novakova Finance", country: "Czech Republic", avatar: "KN", rating: 5, text: "Invoice automation sends, tracks, and reminds automatically. Accounts receivable days dropped from 45 to 22 and our team spends 70% less time on collections." },
      { name: "Damian Kubiak", role: "CEO", company: "Kubiak Holdings", country: "Poland", avatar: "DK", rating: 5, text: "Automated reporting delivers our 12 weekly reports to stakeholders every Monday morning without anyone touching it. Hours saved every week, consistently." },
      { name: "Nina Sato", role: "Admin Manager", company: "Sato Enterprises", country: "Japan", avatar: "NS", rating: 4, text: "Data entry automation between our 4 core business systems eliminated the manual syncing our admin team spent 3 hours daily doing. Total game changer." },
    ],
    demoType: "admin-automation",
  },
  {
    slug: "analytics",
    title: "Reporting & Analytics",
    shortDesc: "Real-time dashboards giving you complete visibility into business performance.",
    heroHeadline: "Stop Guessing. Start Knowing.",
    heroSubtext: "We build real-time reporting dashboards and custom analytics systems that give you complete, instant visibility into your business performance — so every decision is data-driven.",
    features: [
      { title: "Executive Dashboards", desc: "Real-time C-suite dashboards showing KPIs, revenue, and operational metrics at a glance." },
      { title: "Sales & Revenue Analytics", desc: "Pipeline performance, conversion funnels, and revenue attribution by channel." },
      { title: "Marketing Performance Reports", desc: "Cross-channel marketing analytics connecting spend to revenue." },
      { title: "Operational KPI Tracking", desc: "Live monitoring of throughput, SLA compliance, and efficiency metrics." },
      { title: "Predictive Analytics", desc: "Forecast models that predict revenue, churn, demand, and resource needs." },
      { title: "Custom Data Integrations", desc: "Pull data from any source into a unified analytics layer for single-source-of-truth reporting." },
    ],
    caseStudies: [
      {
        company: "Copper & Pine Restaurant Group",
        country: "United States",
        flag: "🇺🇸",
        industry: "Hospitality / Multi-Site Dining",
        challenge: "Copper & Pine owned 5 casual dining restaurants in Portland but had no visibility into performance across locations — owners reviewed printed daily sales summaries from each manager, often 2-3 days behind, with no way to spot trends or problems quickly.",
        solution: "Built a unified real-time analytics dashboard pulling POS, labour scheduling, food cost, and reservation data from all 5 sites — giving owners a single live view of revenue, margins, and table turn rates by location and day-part.",
        results: [
          "Food cost variance identified and corrected at one location — saving $3,200/month",
          "Labour over-scheduling identified visually for the first time — labour cost reduced 8% group-wide",
          "Owners now review business performance in 10 minutes daily vs. a 3-hour weekly review meeting",
          "Best-performing menu items identified by analytics — menu redesign lifted average check by 12%",
        ],
        metric: "12%",
        metricLabel: "Average Check Value Increase",
      },
      {
        company: "Waverly Wellness Clinics",
        country: "United Kingdom",
        flag: "🇬🇧",
        industry: "Private Healthcare / Physiotherapy",
        challenge: "Waverly operated 3 physiotherapy clinics in Edinburgh and had no way to track which practitioners, services, or referral sources were driving revenue — management ran on gut feel and month-end spreadsheets that nobody fully trusted.",
        solution: "Implemented a reporting and analytics layer over their practice management software — auto-generating weekly performance reports by practitioner, service type, and referral source, with a real-time dashboard accessible on any device.",
        results: [
          "Identified that 2 referral GPs drove 38% of all new patients — partnership deepened proactively",
          "Underperforming service lines identified and replaced — overall revenue up 19% in 9 months",
          "Practitioner utilisation tracking revealed scheduling inefficiencies saving £6,500/month in idle time",
          "Month-end reporting reduced from a 2-day manual process to 15-minute automated delivery",
        ],
        metric: "19%",
        metricLabel: "Revenue Growth in 9 Months",
      },
    ],
    testimonials: [
      { name: "Alex Turner", role: "CEO", company: "Turner Holdings", country: "United Kingdom", avatar: "AT", rating: 5, text: "Executive dashboard built by BVN gives me everything I need in one screen. I can see real-time revenue, pipeline, and operational metrics without waiting for reports." },
      { name: "Marina Costa", role: "Head of Analytics", company: "Costa Capital", country: "Portugal", avatar: "MC", rating: 5, text: "Custom analytics connecting our marketing spend to actual revenue was transformational. We reallocated 40% of our budget to better-performing channels immediately." },
      { name: "Felix Wagner", role: "Operations Director", company: "Wagner Industries", country: "Germany", avatar: "FW", rating: 4, text: "Real-time operational dashboards replaced our monthly Excel reports. We now catch issues within hours instead of discovering them weeks later at month-end." },
      { name: "Amira Khalil", role: "CFO", company: "Khalil Group MENA", country: "UAE", avatar: "AK", rating: 5, text: "Financial reporting that previously took our team 3 days each month is now automated and delivered in real time. Accuracy improved and our audit process is far simpler." },
      { name: "Scott MacLeod", role: "Founder", company: "MacLeod Digital", country: "Scotland", avatar: "SM", rating: 5, text: "BVN integrated data from 7 different systems into one unified dashboard. For the first time we have a single version of the truth across the whole business." },
      { name: "Laila Abdi", role: "Marketing Director", company: "Abdi Ventures", country: "Kenya", avatar: "LA", rating: 4, text: "Cross-channel marketing attribution dashboard revealed which campaigns actually drove revenue. We cut wasteful spend by 35% with full confidence in the data." },
      { name: "Erik Holm", role: "COO", company: "Holm Shipping", country: "Norway", avatar: "EH", rating: 5, text: "Operational KPI dashboards for our fleet gave real-time visibility we never had before. Fuel efficiency improved 12% and on-time delivery improved 23%." },
    ],
    demoType: "analytics",
  },
  {
    slug: "integrations",
    title: "System Integrations",
    shortDesc: "Connect all your tools into one seamless, automated business ecosystem.",
    heroHeadline: "One Business. One Connected System.",
    heroSubtext: "We connect your existing tools — CRM, accounting, e-commerce, HR, and beyond — into one seamless automated ecosystem where data flows freely and nothing falls through the cracks.",
    features: [
      { title: "API Integrations", desc: "Custom API connections between any two systems in your technology stack." },
      { title: "E-commerce Integrations", desc: "Connect your store, inventory, shipping, and accounting for end-to-end automation." },
      { title: "Accounting Integrations", desc: "Sync sales, invoices, and payments between your CRM and accounting software." },
      { title: "Communication Tool Integrations", desc: "Connect Slack, Teams, and email with your core business systems." },
      { title: "iPaaS Platform Automation", desc: "Zapier, Make (Integromat), and custom middleware for complex multi-step automations." },
      { title: "Real-Time Data Sync", desc: "Bidirectional data synchronization ensuring every system always has current data." },
    ],
    caseStudies: [
      {
        company: "Outpost Outdoor Gear",
        country: "United States",
        flag: "🇺🇸",
        industry: "Outdoor & Sporting Goods Retail",
        challenge: "Outpost ran a Shopify storefront alongside a physical store in Denver — but inventory, accounting (QuickBooks), and their email marketing platform were completely siloed, requiring 3 hours of manual data syncing every day and causing frequent overselling online.",
        solution: "Built a seamless integration connecting Shopify, QuickBooks, their in-store POS, and Klaviyo — real-time inventory sync across both channels, automatic accounting entries on every sale, and purchase data flowing into segmented email lists.",
        results: [
          "Overselling incidents eliminated completely — inventory updates across all channels in under 60 seconds",
          "Daily manual data syncing of 3 hours reduced to zero — fully automatic across all systems",
          "Monthly accounting close shortened from 3 days to half a day with automatic reconciliation",
          "Email revenue increased 34% as purchase data triggered automated product recommendation sequences",
        ],
        metric: "34%",
        metricLabel: "Email Revenue Increase",
      },
      {
        company: "Mercer Recruitment",
        country: "Australia",
        flag: "🇦🇺",
        industry: "Specialist Recruitment Agency",
        challenge: "Mercer, a 20-person technology recruitment firm in Sydney, used 5 disconnected tools — their ATS, CRM, LinkedIn Recruiter, accounting software, and a separate email client — with no data flowing between them, forcing consultants to re-enter candidate data repeatedly.",
        solution: "Integrated all 5 systems using Make.com and custom API connectors — new candidates from LinkedIn auto-populate the ATS, placed candidates trigger invoices in Xero automatically, and CRM updates when deal stages change in the ATS.",
        results: [
          "Consultant time on manual data entry reduced from 90 minutes to under 10 minutes per placement",
          "Invoice generation on placement became instant and error-free vs. a 2-day manual process",
          "Candidate data quality improved 60% — no more inconsistencies between systems",
          "Consultants placed 2.3 more candidates per month on average — time saved redirected to sourcing",
        ],
        metric: "2.3",
        metricLabel: "Extra Placements Per Consultant Monthly",
      },
    ],
    testimonials: [
      { name: "Philip Carter", role: "Technology Director", company: "Carter Group International", country: "United Kingdom", avatar: "PC", rating: 5, text: "BVN connected our CRM, accounting, and e-commerce systems perfectly. Reconciliation that took 2 days now happens in real time. No more duplicate data entry anywhere." },
      { name: "Elisa Fontana", role: "COO", company: "Fontana Commerce", country: "Italy", avatar: "EF", rating: 5, text: "Shopify-to-Xero integration built by BVN is flawless. Financial reports are always accurate and up-to-date without anyone touching them." },
      { name: "Dylan Carmichael", role: "Founder", company: "Carmichael Agency", country: "Australia", avatar: "DC", rating: 4, text: "Slack integrations for our project management workflow saved our team 8 hours per week in tool switching and manual status updates." },
      { name: "Nkechi Okafor", role: "Head of Tech", company: "Okafor Fintech", country: "Nigeria", avatar: "NO", rating: 5, text: "Complex API integrations between 6 systems were handled expertly. Documentation was thorough and everything has worked reliably for 14 months straight." },
      { name: "Luca Ferrari", role: "Operations Manager", company: "Ferrari Logistics", country: "Italy", avatar: "LF", rating: 5, text: "End-to-end supply chain integration from order to delivery to accounting is seamless now. We eliminated 3 manual handoff steps and 100% of the errors that came with them." },
      { name: "Astrid Berglund", role: "Digital Manager", company: "Berglund Retail", country: "Sweden", avatar: "AB", rating: 4, text: "E-commerce integrations have transformed our operations. Inventory, orders, and shipping update across all systems simultaneously — our team is 40% more productive." },
      { name: "Kweku Mensah", role: "CTO", company: "Mensah Digital", country: "Ghana", avatar: "KM", rating: 5, text: "BVN built a Make.com automation that orchestrates 12 different tools in our business. It runs 24/7 and handles hundreds of workflow steps daily without errors." },
    ],
    demoType: "integrations",
  },
];

export function getOperationsService(slug: string): OperationsService | undefined {
  return operationsServices.find((s) => s.slug === slug);
}
